config/routes.rb
Rails.application.routes.draw do
  root to: 'patient#index'
  resources :patient
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admission.rb
class Admission < ApplicationRecord
  belongs_to :patient
  has_many  :admission_diagnoses, as: :diagnosable
  has_many  :symptoms
  has_many  :observations

  alias_attribute :diagnoses, :admission_diagnoses


end

app/models/admission_diagnosis.rb
class AdmissionDiagnosis < MedicalDiagnosis

end

app/models/allergy.rb
class Allergy < ApplicationRecord
  belongs_to  :patient

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chronic_condition.rb
class ChronicCondition < MedicalDiagnosis
end

app/models/diagnostic_procedure.rb
class DiagnosticProcedure < ApplicationRecord
  belongs_to  :patient


  def self.explain_in_words(collection)
    output = []
    collection.each do |procedure|
      output << procedure.description.titleize + " on " + procedure.moment.strftime("%B %d, %Y at %I:%M %p ")
    end
    return output.to_sentence
  end

end

app/models/facility.rb
class Facility < ApplicationRecord
  has_many  :patients
end

app/models/medical_diagnosis.rb
class MedicalDiagnosis < ApplicationRecord
  belongs_to :diagnosable, polymorphic: true

  def self.explain_in_words(collection)
    output = []
    collection.each do |diagnosis|
      output << "#{diagnosis.description} (#{diagnosis.code})"
    end

    return output.to_sentence
  end
end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord
  belongs_to  :patient
  has_one :frequency, class_name: 'OrderFrequency'

  enum mass_unit: {mg: 0}
  enum medication_route: {PO: 0, IM: 1, SC: 2}


  def self.explain_in_words(collection)
    output = []
    collection.each do |medication|
      output << " #{medication.name } #{medication.dosage.to_i.to_s + medication.mass_unit} #{medication.medication_route} #{medication.frequency.value.to_s + medication.frequency.frequency_unit} to #{medication.necessity}"
    end

    return output.to_sentence
  end

end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to  :admission
end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord

  enum frequency_unit: {hr: 0}
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :facility
  has_one  :admission
  has_many :allergies
  has_many :patient_diagnoses, as: :diagnosable
  has_many :chronic_conditions, as: :diagnosable
  has_many :medications, class_name: 'MedicationOrder'
  has_many :diagnostic_procedures
  has_many :treatments

  alias_attribute :diagnoses, :patient_diagnoses

  enum gender: {male: 0, female: 1, other: 2}


  def age
    age = (DateTime.now - self.dob.to_date) / 365.25
    return age.round
  end

end

app/models/patient_diagnosis.rb
class PatientDiagnosis < MedicalDiagnosis
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  belongs_to  :admission
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  belongs_to  :patient

  def self.explain_in_words(collection)
    output = []
    collection.each do |treatment|
      output << "#{treatment.description}  to #{treatment.necessity}"
    end

    return output.to_sentence
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
    @admission = @patient.admission
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def datetime_sentence(datetime)
    return datetime.strftime("%B %d, %Y at %I:%M %p ")
  end
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StBern</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header clearfix">
      <h3 class="text-muted title"> StBern EMR  </h3>
      <hr>
    </div>
    <%= yield %>
  </body>
</html>

app/views/patient/index.html.erb
<div class="container">
  <div class=" form-header">
    <h3 class="form-title">Patients List </h3>
    <hr>
  </div>
  <table class="table">
    <tr>
      <th>Medical Record (MR)</th>
      <th>Patient First Name</th>
      <th>Patient Last Name</th>
      <th>Faciltiy</th>
      <th>Admissions Date</th>
    </tr>
    <% @patients.each do |patient| %>
        <tr>
          <td>
            <%= link_to patient.mr, patient_path(patient), class: "btn btn-default btn-xs" %>
          </td>
          <td>
            <%= patient.first_name %>
          <td>
            <%= patient.last_name %>
          </td>
          <td>
            <%= patient.facility.name %>
          </td>
          <td>
            <%= patient.admission.moment.to_date %>
          </td>
        </tr>
    <% end %>

  </table>
</div>

app/views/patient/show.html.erb
<div class="container">
  <div class=" form-header">
    <h3 class="form-title">Emergency Transfer Summary (Form 34L-D) </h3>
    <hr>
  </div>
  <div class="col-md-12">
    <div class="row bordered">
      <h3> Transferring Facility</h3>
    </div>
    <div class="row bordered">
      <div class="col-md-4 bordered">
        <strong>Name</strong>
        <br>
        <%= @patient.facility.name %>
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <div class="row bordered">
      <h3> Patient Information </h3>
    </div>
    <div class="row bordered">
      <div class="col-md-2 bordered">
        <strong>First Name</strong>
        <br>
        <%= @patient.first_name %>
      </div>
      <div class="col-md-2 bordered">
        <strong>Middle Name</strong>
        <br>
        <%= @patient.middle_name %>
      </div>
      <div class="col-md-2 bordered">
        <strong>Last Name</strong>
        <br>
        <%= @patient.last_name %>
      </div>
      <div class="col-md-2 bordered">
        <strong>Medical Record (MR)</strong>
        <br>
        <%= @patient.mr%>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="row bordered">
      <h3> Summary </h3>
    </div>
    <div class="row bordered">
      <div class="col-md-12 bordered">

        <%= render 'shared/admission_summary' %>

      </div>


    </div>
  </div>






</div>

app/views/shared/_admission_summary.erb
<p class="text-justify">
  This <%= pluralize(@patient.age, "years")%> old <%= @patient.gender %> was admitted to <%= @patient.facility.name %>
  on <%= datetime_sentence(@admission.moment) %> due to <%= MedicalDiagnosis.explain_in_words(@admission.diagnoses) %>.
  The observed symptoms on admission were <%= @admission.symptoms.pluck(:description).to_sentence %>.
  <%= @admission.observations.pluck(:description).to_sentence %>.
  <br><br>
  Upon asking about known allergies, the patient
  disclosed <%= @patient.allergies.pluck(:description).to_sentence %> allergy. Upon asking about chronic
  conditions, the patient disclosed
  <%= MedicalDiagnosis.explain_in_words(@patient.chronic_conditions) %>. The patient was administered with
  <%= MedicationOrder.explain_in_words(@patient.medications) %>
  <br><br>
  The staff performed <%= DiagnosticProcedure.explain_in_words(@patient.diagnostic_procedures)%>, revealing
  <%= MedicalDiagnosis.explain_in_words(@patient.diagnoses) %>. Our team proceeded to
  <%= Treatment.explain_in_words(@patient.treatments) %>.
</p>